config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'admin', to: 'pages#login'
  get 'nosotros', to: 'pages#nosotros'

  resources :ancheta
  get '/anchetas', to: 'ancheta#new'

  root 'pages#index'

end

app/models/anchetum.rb
class Anchetum < ActiveRecord::Base
	serialize :descripcion, Array

	validates :nombre, :presence => true
	validates :celular, :presence => true
	validates :descripcion, :presence => true
end

app/controllers/ancheta_controller.rb
class AnchetaController < ApplicationController
  before_action :set_anchetum, only: [:show, :edit, :update, :destroy]

  # GET /ancheta
  # GET /ancheta.json
  def index
    if params[:clave] == "Diosesnuestrabendicion"
      @ancheta = Anchetum.all
    else
      redirect_to anchetas_path
    end
  end

  # GET /ancheta/new
  def new
    @anchetum = Anchetum.new
    @body = true
  end

  # GET /ancheta/1/edit
  def edit
  end

  # POST /ancheta
  # POST /ancheta.json
  def create
    @anchetum = Anchetum.new(anchetum_params)
    @body = true

    respond_to do |format|
      if @anchetum.save
        format.html { redirect_to root_path, notice: 'Anchetum was successfully created.' }
        format.json { render :show, status: :created, location: @anchetum }
      else
        format.html { render :new }
        format.json { render json: @anchetum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ancheta/1
  # PATCH/PUT /ancheta/1.json
  def update
    respond_to do |format|
      if @anchetum.update(anchetum_params)
        format.html { redirect_to @anchetum, notice: 'Anchetum was successfully updated.' }
        format.json { render :show, status: :ok, location: @anchetum }
      else
        format.html { render :edit }
        format.json { render json: @anchetum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ancheta/1
  # DELETE /ancheta/1.json
  def destroy
    @anchetum.destroy
    respond_to do |format|
      format.html { redirect_to ancheta_url, notice: 'Anchetum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anchetum
      @anchetum = Anchetum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anchetum_params
      params.require(:anchetum).permit(:nombre, :celular, :direccion, descripcion: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def login
  end
  def nosotros
  	@body = "normal"
  end
end

app/helpers/ancheta_helper.rb
module AnchetaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ancheta/_form.html.erb
  <% if @anchetum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anchetum.errors.count, "error") %> prohibited this anchetum from being saved:</h2>

      <ul>
      <% @anchetum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="obligatorio"></span>
    <%= f.text_field :nombre, placeholder: "Nombre y apellido" %>
    <span class="obligatorio"></span>
  </div>
  <div class="field">
    <%= f.number_field :celular, placeholder: "Numero de Contacto" %>
  </div>
  <div class="field">
    <%= f.text_field :direccion, placeholder: "Direccion" %>
  </div>
  <div class="field">
    <input type="checkbox" name="anchetum[descripcion][]" id="campaign_channels_Folder" value="Folder" />
    <input type="checkbox" name="anchetum[descripcion][]" id="campaign_channels_Campana" value="Campana" />
  </div>
  <div class="actions">
    <%= f.submit "Te llamaremos"%>
  </div>

app/views/ancheta/edit.html.erb
<h1>Editing Anchetum</h1>

<%= render 'form' %>

<%= link_to 'Show', @anchetum %> |
<%= link_to 'Back', ancheta_path %>

app/views/ancheta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ancheta</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Celular</th>
      <th>Direccion</th>
      <th>Ancheta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ancheta.each do |anchetum| %>
      <tr>
        <td><%= anchetum.nombre %></td>
        <td><%= anchetum.celular %></td>
        <td><%= anchetum.direccion %></td>
        <td><%= anchetum.descripcion %></td>
        <td><%= link_to 'Destroy', anchetum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-32x32.png' %>" sizes="32x32">
<link rel="icon" type="image/png" href="<%= asset_path 'favicon/favicon-16x16.png' %>" sizes="16x16">
<link rel="manifest" href="<%= asset_path 'favicon/manifest.json' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#2f6ab2">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Proveedor">
<meta name="application-name" content="Proveedor">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>El Proveedor | Anchetas</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--Favicones-->
	<%= render 'application/favicon' %>


  <!--Hojas de Estilos-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">



  <!--Hojas de Js-->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<% if @body == true %>
	<body id="anchetas">
<% elsif @body == "normal" %>
	<body id="normal">
<% else %>
	<body>
<% end %>
<header class="header"> <!-- Cabezera del Homepage -->
	<figure>
		<h2>EL PROVEEDOR</h2>
	</figure>
	<nav class="navigation">
		<ul>
		    <li>
		        <%= link_to 'Inicio', root_path %>
		    </li>
		    <li>
		        <%= link_to 'Nosotros', nosotros_path %>
		    </li>
		    <li>
		        <%= link_to 'Anchetas', anchetas_path %>
		    </li>
	    </ul>
	</nav>
</header>

<%= yield %>

<script type="text/javascript">
	
    	$('#fullpage').fullpage({
			sectionsColor: ['#7BAABE', '#ffffff', '#2f2f2f'],
			navigation: true
    	});
		
</script>
<%= tawk_init %>


<script type="text/javascript">
	$( ".1" ).click(function() {
  		$( "#1" ).toggle();
  		$( "#1" ).toggleClass( "cantcarrito" );
	});
	$( ".2" ).click(function() {
  		$( "#2" ).toggle();
  		$( "#2" ).toggleClass( "cantcarrito" );
	});
	$( ".3" ).click(function() {
  		$( "#3" ).toggle();
  		$( "#3" ).toggleClass( "cantcarrito" );
	});
	$( ".4" ).click(function() {
  		$( "#4" ).toggle();
  		$( "#4" ).toggleClass( "cantcarrito" );
	});
	$( ".5" ).click(function() {
  		$( "#5" ).toggle();
  		$( "#5" ).toggleClass( "cantcarrito" );
	});
	$( ".6" ).click(function() {
  		$( "#6" ).toggle();
  		$( "#6" ).toggleClass( "cantcarrito" );
	});
	$( ".7" ).click(function() {
  		$( "#7" ).toggle();
  		$( "#7" ).toggleClass( "cantcarrito" );
	});
	$( ".8" ).click(function() {
  		$( "#8" ).toggle();
  		$( "#8" ).toggleClass( "cantcarrito" );
	});
	$( ".9" ).click(function() {
  		$( "#9" ).toggle();
  		$( "#9" ).toggleClass( "cantcarrito" );
	});
	$( ".10" ).click(function() {
  		$( "#10" ).toggle();
  		$( "#10" ).toggleClass( "cantcarrito" );
	});
	$( ".11" ).click(function() {
  		$( "#11" ).toggle();
  		$( "#11" ).toggleClass( "cantcarrito" );
	});
	$( ".12" ).click(function() {
  		$( "#12" ).toggle();
  		$( "#12" ).toggleClass( "cantcarrito" );
	});
	$( ".13" ).click(function() {
  		$( "#13" ).toggle();
  		$( "#13" ).toggleClass( "cantcarrito" );
	});
	$( ".14" ).click(function() {
  		$( "#14" ).toggle();
  		$( "#14" ).toggleClass( "cantcarrito" );
	});
	$( ".15" ).click(function() {
  		$( "#15" ).toggle();
  		$( "#15" ).toggleClass( "cantcarrito" );
	});
	$( ".16" ).click(function() {
  		$( "#16" ).toggle();
  		$( "#16" ).toggleClass( "cantcarrito" );
	});
</script>
    <!-- Initialize Swiper -->
    <script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        spaceBetween: 30,
        centeredSlides: true,
        autoplay: 3500,
        autoplayDisableOnInteraction: false
    });
    </script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88512900-1', 'auto');
  ga('send', 'pageview');

</script>
<script>
	$( ".precio" ).click(function() {
	  $( this ).toggleClass( "comprado" );
	});
</script>
<script>
	$( ".precio" ).click(function() {
	  $( this ).find("p").toggle();
	});
</script>


<script>
$( ".pedir-ancheta, .ion-backspace-outline" ).click(function() {
  $( ".ventana-emergente" ).toggleClass( "abierta" );
});
</script>
<script>
	$(".carrito").click(function () {
		cant = $('.cantcarrito').size();
	    $(".pedir-ancheta-circle").text( cant );
	});

</script>

</body>
</html>

app/views/pages/index.html.erb
<div id="fullpage">

    <div class="section">
	    <div class="hero">
			<h1>EL PROVEEDOR</h1>
			<p>Comparte la navidad con nosotros</p>
			<%= link_to  anchetas_path ,class: 'btn' do %>
                <div class="effect-btn"></div>
                <p>VER ANCHETAS Y MATRIMONIOS</p>
            <% end %>
	    </div>
    </div>
    <div class="section slide">
            <!-- Swiper -->
    <div class="swiper-container">
        <div class="swiper-wrapper">
            <div class="swiper-slide"><%= image_tag("SLIDE 1.png", width: '100%') %></div>
            <div class="swiper-slide"><%= image_tag("SLIDE 2.png", width: '100%') %></div>
            <div class="swiper-slide"><%= image_tag("SLIDE 3.png", width: '100%') %></div>
            <div class="swiper-slide"><%= image_tag("SLIDE 4.png", width: '100%') %></div>
        </div>
        <!-- Add Pagination -->
        <div class="swiper-pagination"></div>
    </div>


    </div>
    <div class="section locat">
    	<div class="location">
        <div class="footer">
            <div>
                <span class="ion-social-instagram-outline"></span>
                <span class="ion-social-facebook-outline"></span>
                <span class="ion-social-twitter-outline"></span>
            </div>
            <hr>
            <div class="datos">
                <p>Tel +(8) 6608393 | comercialelproveedorsas@hotmail.com</p>
                <p>© 2016, Comercial El Proveedor S.A.S</p>
            </div>
        </div>
    	<div>
	    	<iframe class="map-location" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6692.581560886729!2d-73.6143486600396!3d4.134941288655215!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3e2e7bcedd9cad%3A0xd71694cd4e6fc17b!2sEl+Proveedor!5e0!3m2!1ses-419!2ses!4v1480791315145" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	    	<h2>Villavicencio-Meta, Colombia</h2>
    	</div>

    	</div>
    </div>

</div>

app/views/pages/login.html.erb
<div class="login-admin">    
    <%= form_tag("/ancheta", method: "get") do %>
      <%= label_tag(:clave, "clave:") %>
      <%= password_field_tag(:clave) %>
      <%= submit_tag("ingresar") %>
    <% end %>
</div>

app/views/pages/nosotros.html.erb
<div class="nosotros">
	<h1>Quiénes somos</h1>
	<h2>Misión.</h2>

	<p>Somos  una  empresa  metense  especializada en  el  servicio  y  comercialización de  productos  alimenticios  como:  lácteos,  panadería,  huevos,  carnes  frías, enlatados,  snacks, galletas,  dulces nacionales  e importados,  víveres, licores  y abarrotes con los mejores estándares de calidad e inocuidad.  Garantizamos  nuestros  procesos  mediante  un  personal  altamente  calificado, equipos  e  infraestructura  establecidos  logrando  dar  satisfacción  mediante  la adquisición  de  los  productos  por  medio  de  los  proveedores  hacia  nuestros clientes,  logrando  un  mejoramiento  continuo  del  proceso  de la  venta  y/osuministro de productos alimenticios.</p>

	<h2>Visión.</h2>

	<p>COMERCIAL EL PROVEEDOR SASpara el 2025  va ser una empresa  líder de   comercialización   y   suministro   de   productos   alimenticios   de   la   región Orinoquia,  estableciendo  sucursales  y  una  tienda  virtual    para garantizar  el cumplimiento eficiente de las actividades brindando satisfacer las necesidades de  los  clientes  en  las  diferentes  ciudades  de  la  Orinoquia  manteniendo  un mejoramiento  continuo  con  la    implementación  de  equipos  y tecnologías    que permita hacer eficiente los procesos.</p>

	<h2>Politica Integral.</h2>
	
	<p>Somos  una  empresa  dedicada  a  la  comercialización  de    productos alimenticios   inocuos   y   de   alta   calidad,   garantizando   un   eficiente desarrollo de las actividades por parte de personal calificado, equipos e infraestructura, asignando los recursos necesarios para lograr mantener una  mejora  continua,  permitiendo  mitigar  lesiones,   y  desechos  que contaminen,  cumpliendo  la  legislación  correspondiente  garantizando  la satisfacción  de  nuestros clientes.</p>

</div>